config/routes.rb
Rails_Project::Application.routes.draw do

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  resources :messages

  match '/faq' => "static#faq.html.erb"

  resources :courses  

  resources :categories

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>

  <% if msg.class == Array %>
    <% msg.each do |message| %>
      <%= content_tag :div, message, :id => "flash_#{name}" %>
    <% end %>
  <% else %>

    <%= content_tag :div, msg, :id => "flash_#{name}" %>

  <% end %> 
<% end %>

app/views/layouts/_navigation.html.erb
<div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <div class="container nav-collapse">
            <ul class="nav">
              <li>
                <%= link_to "UCC Summer Courses", root_path, :class => 'brand' %>
              </li>
              <li>
                <%= link_to 'Categories', categories_path%>
              </li>
              <li>
                <%= link_to 'Contact Us', new_message_path %>
              </li>
              <li>
                <%= link_to 'FAQ', '/faq' %>
              </li>
              <% if user_signed_in? %>
              <li class="pull-right">
                <%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %>
              </li>
             <% else %>
               <li class="pull-right">
               <%= link_to 'Login', new_user_session_path %>
               </li>
              <% end %>
              <% if user_signed_in? %>
                <li>
                  <%= link_to 'Edit account', edit_user_registration_path %>
                </li>
              <% else %>
                <li class="pull-right">
                  <%= link_to 'Sign up', new_user_registration_path %>
                </li>
              <% end %>
              <% if can? :access, :rails_admin %> 
                <li><%= link_to 'Admin Dashboard', rails_admin_path %></li>
              <%end%>
            </ul>
           </div><!--/.nav-collapse -->
        </div>
        </div>
      </div>


<div class="container">
        <div class="row-fluid">
          <div class="span9">
            <%= bootstrap_flash %>
            <%= yield %>
          </div>
          <div class="span3">
            <div class="well sidebar-nav pull-right">
              <ul class="nav nav-pills nav-stacked">
                <li ><%= link_to 'Categories', categories_path %>
                </li>
                <% if user_signed_in? %>
                  <% if can? :access, :rails_admin %> 
                    <li>
                      <%= link_to 'Admin Dashboard', rails_admin_path %>
                    </li>
                  <%end%>
                  <li>
                    <div><%= link_to 'Logout', destroy_user_session_path, :method=>'delete', :class => "btn btn-primary" %></div>
                  </li>
                <%else%>
                  <%= form_for(resource, :as => resource_name, :url => session_path(resource_name)) do |f| %>
                  <div class="form-actions">
                    <li>
                      <%= f.label :login %>
                      <%= f.text_field :login %>
                    </li>
                    <li>
                      <%= f.label :password %>
                      <%= f.password_field :password %>
                    </li>
                    <li>
                      <div><%= f.submit "Sign in", :class => "btn btn-primary"%></div>
                    </li>
                     <li class="nav-header">Sign up</li>
                    <li>
                      <div><%= link_to 'Sign up', new_user_registration_path, :class => "btn btn-secondary" %></div>
                    </li>
                  </div>
                  <%end%>
                <%end%>
              </ul>
            </div><!--/.well -->
          </div><!--/span-->
        </div><!--/row-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "UCC Summer Courses" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>
  <%= render 'layouts/navigation' %>

      <footer>
        <p>&copy; Team 17</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>